################################################
## The Main Config-File for GuestUnlock!       #
## Coded by Myller for  http://tehwarriors.net #
################################################


################################################
##########     Main Configuration     ##########
################################################

Guest:
    Join:
        Enable: true
        Message: Welcome Guest! I think that you should read the rules! Use "/guestunlock [password]" to unlock!
    RepeatingMessage:
        Interval: 60
        UseJoinMessage: true
        RepeatMessage: null
    Responds:
        Correct: The password was correct!
        Incorrect: The password was incorrect!
Admin:
    Password: GuestUnlock
    SendIncorrectMessageToMods: false
    Debug: false
Permissions:
    SendMessageOnGroupChange: true
    PermissionsEx:
        Group:
            Build: builder
            Default: default
        Enable: false
    GroupManager:
        Group:
            Build: builder
            Default: default
        Enable: false
    bPermissions:
        Group:
            Build: builder
            Default: default
        Enable: false

################################################
###########    Configuration Help    ###########
################################################
# Example:
#    Example:
#       Option: 'DataType', what this does.

# GUEST:
    # Join:
        # Enable: boolean, enable joinmessages to guests
        # Message string, the join message for guests, it also sends this message at the specified interval 
    # RepeatingMessage:
            # Interval: int, must be in seconds, must be an integer, interval which decides when the Message is sent.
            # UseJoinMessage: boolean, If the repeating message should be the same as the joinmessage.
            # RepeatMessage: string, If 'UseJoinMessage' = false this message is sent instead.
    # Responds:
        # Correct: string, Message to the player when he enters the correct password.
        # Incorrect: string, Message to the player when he enters the incorrect password.
        
# ADMIN
    # Password: string, the correct password.
    # SendIncorrectMessageToMods: boolean, send a message to moderators when a player sends the wrong password?
# PERMISSIONS:    
    # SendMessageOnGroupChange: boolean, Send a message to moderators online when a player sends the correct password and is moved to the build group
    # PERMISSIONEX/GROUPMANAGER/BPERMISSIONS
        # Group: 
            # Default: string, The group the player has to be in to be moved to the build group
            # Build: string, The group the player are moved to when sending the correct password
        # Enable: boolean, If this function shall be enabled 
    
################################################
###########        Datatypes         ###########
################################################ 
# Boolean: true/false //Simple yes or no..
# String: A simple text string //Just text..
# Int: 60 //An Integer..